### ISSUE TITLE
[BUG] Training Threshold set to incorrect value when no value is set in command

### ISSUE THREAD

**Issue by kassieclaire** [blaisewf/RVC_CLI#44]
**Describe the bug**
Get the following error, whether overtrain_detector is set to true/false and whether overtrain_threshold is set to an integer value or not:
train.py: error: argument -ot/--overtraining_threshold: invalid int value: 'False'
**To Reproduce**
Run with the following options:
{python_path} main.py train --model_name {model_name} --sampling_rate 40000 --pitch_guidance True --gpu 1 --save_every_epoch 50 --save_only_latest True --overtraining_detector False

**Expected behavior**
Training runs and completes

**Assets**
If applicable, add screenshots/videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by blaise-tk** [comment]
all the values should be passed as an string

**Comment by kassieclaire** [comment]
Error also occurs when command is put directly into the CLI (rather than ran using Python's subprocess module)
