### ISSUE TITLE
[BUG] RVC doesn't produce a usable result with default settings

### ISSUE THREAD

**Issue by Eyalm321** [blaisewf/RVC_CLI#57]
Hey guys,

I was able to get the server started and configured to work, tts is working too after changing locale to shortname.
So im getting tts output but rvc output is just interference, like a continuous beep. also when performing inference, it works well on the original and the fork with the same model, do I need special type of model here?

tried both api and cli.

**Comment by blaise-tk** [comment]
download from https://github.com/blaise-tk/RVC_CLI/releases/tag/1.2.0

**Comment by Eyalm321** [comment]
Same result unfortunately, will try previous commits

**Comment by Eyalm321** [comment]
Update:

Hope it helps, last commit that seems to work is b71522e3ebbebcd6c738121ce01f518c71da31db
